/*
  Warnings:

  - The values [PRODUCT_UPDATED] on the enum `NotificationType` will be removed. If these variants are still used in the database, this will fail.

*/
-- AlterEnum
BEGIN;
CREATE TYPE "NotificationType_new" AS ENUM ('ORDER_PLACED', 'ORDER_PAID', 'ORDER_CANCELED', 'PURCHASE_ORDER_CREATED', 'PURCHASE_ORDER_FUNDED', 'PURCHASE_ORDER_STATUS_UPDATE', 'RIDER_ASSIGNED', 'RIDER_DELIVERED', 'PAYMENT_FAILED', 'PRODUCT_SUBMITTED', 'PRODUCT_APPROVED', 'PRODUCT_REJECTED', 'PRODUCT_DISABLED', 'PRODUCT_DELETED', 'REFUND_REQUESTED', 'REFUND_STATUS_CHANGED', 'DISPUTE_OPENED', 'DISPUTE_STATUS_CHANGED', 'SUPPLIER_PAYOUT_RELEASED', 'SUPPLIER_PAYOUT_HELD', 'SUPPLIER_PAYOUT_FAILED', 'SUPPLIER_REVIEW_RECEIVED', 'SUPPLIER_KYC_STATUS_CHANGED', 'SUPPLIER_BANK_STATUS_CHANGED', 'SUPPLIER_OFFER_CHANGE_SUBMITTED', 'SUPPLIER_OFFER_CHANGE_APPROVED', 'SUPPLIER_OFFER_CHANGE_REJECTED', 'PRODUCT_CHANGE_SUBMITTED', 'PRODUCT_CHANGE_APPROVED', 'PRODUCT_CHANGE_REJECTED', 'GENERIC');
ALTER TABLE "Notification" ALTER COLUMN "type" TYPE "NotificationType_new" USING ("type"::text::"NotificationType_new");
ALTER TYPE "NotificationType" RENAME TO "NotificationType_old";
ALTER TYPE "NotificationType_new" RENAME TO "NotificationType";
DROP TYPE "public"."NotificationType_old";
COMMIT;
