services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: yemi
      POSTGRES_PASSWORD: yemipass
      POSTGRES_DB: yemisshop
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
